# Generated by Django 5.2.4 on 2026-07-23 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalevent',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to='expenses.expensereport'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='expenses.expensereport'),
        ),
        migrations.AddIndex(
            model_name='approvalevent',
            index=models.Index(fields=['report', 'created_at'], name='approval_event_report_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalevent',
            index=models.Index(fields=['actor', 'created_at'], name='approval_event_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['report', 'step_order'], name='approval_step_report_order_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approver', 'status'], name='approval_step_approver_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(('step_order__gt', 0)), name='approval_step_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('report', 'step_order'), name='approval_step_report_order_unique'),
        ),
    ]
