# Generated by Django 5.2.4 on 2026-08-18 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('currency', models.CharField(max_length=3)),
                ('threshold_minor', models.BigIntegerField(default=0)),
                ('approver_role', models.CharField(blank=True, choices=[('APPROVER', 'Approver'), ('ADMIN', 'Admin')], max_length=16, null=True)),
            ],
            options={
                'ordering': ['priority', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user__full_name', 'user__email'],
            },
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='origin',
            field=models.CharField(choices=[('RULE', 'Generated by rule'), ('MANUAL', 'Assigned by admin'), ('DELEGATED', 'Delegated')], default='MANUAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='approvalevent',
            name='action',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('AUTO_APPROVED', 'Auto approved'), ('REJECTED', 'Rejected'), ('DELEGATED', 'Delegated'), ('COMMENTED', 'Commented'), ('RETURNED_TO_DRAFT', 'Returned to draft'), ('PAID', 'Paid')], max_length=24),
        ),
    ]
