# Generated by Django 5.2.4 on 2026-08-18 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approval_rules_and_step_candidates'),
        ('expenses', '0002_initial'),
        ('users', '0002_org_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrule',
            name='approver_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules_by_approver_department', to='users.orgattribute'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='approver_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules_by_approver_location', to='users.orgattribute'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='approver_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules_by_approver_position', to='users.orgattribute'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='submitter_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules_by_submitter_department', to='users.orgattribute'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='submitter_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules_by_submitter_location', to='users.orgattribute'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='submitter_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules_by_submitter_position', to='users.orgattribute'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to='approvals.approvalrule'),
        ),
        migrations.AddField(
            model_name='approvalstepcandidate',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='approvals.approvalstep'),
        ),
        migrations.AddField(
            model_name='approvalstepcandidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_candidacies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['active', 'currency', 'category'], name='approval_rule_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['priority'], name='approval_rule_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrule',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_minor__gte', 0)), name='approval_rule_threshold_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='approvalstepcandidate',
            index=models.Index(fields=['user'], name='approval_candidate_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalstepcandidate',
            constraint=models.UniqueConstraint(fields=('step', 'user'), name='approval_step_candidate_unique'),
        ),
    ]
