# Generated by Django 5.2.4 on 2026-07-23 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.expensereport'),
        ),
        migrations.AddField(
            model_name='expensewarning',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warning_rules', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='expensewarning',
            name='warning_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_warnings', to='expenses.warningrule'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['submitted_at'], name='report_submitted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['report', 'status'], name='expense_report_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'expense_date'], name='expense_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expense_category_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['currency'], name='expense_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_at'], name='expense_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gte', 0)), name='expense_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount_minor__gte', 0)), name='expense_tax_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_minor__gte', 0)), name='expense_total_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate_bps__gte', 0), ('tax_rate_bps__lte', 10000)), name='expense_tax_bps_range'),
        ),
        migrations.AddIndex(
            model_name='warningrule',
            index=models.Index(fields=['active'], name='warning_rule_active_idx'),
        ),
        migrations.AddIndex(
            model_name='warningrule',
            index=models.Index(fields=['currency'], name='warning_rule_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='warningrule',
            index=models.Index(fields=['category'], name='warning_rule_category_idx'),
        ),
        migrations.AddIndex(
            model_name='warningrule',
            index=models.Index(fields=['active', 'currency', 'category'], name='warning_rule_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='warningrule',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_minor__gte', 0)), name='warning_rule_threshold_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='expensewarning',
            index=models.Index(fields=['expense', 'created_at'], name='expense_warning_created_idx'),
        ),
        migrations.AddIndex(
            model_name='expensewarning',
            index=models.Index(fields=['warning_rule'], name='expense_warning_rule_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensewarning',
            constraint=models.UniqueConstraint(fields=('expense', 'warning_rule'), name='expense_warning_rule_unique'),
        ),
    ]
