# Generated by Django 5.2.4 on 2026-08-20 10:53

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean')], max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='expenses.expensecategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseFieldValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.CharField(blank=True, default='', max_length=500)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='expenses.expense')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_values', to='expenses.categoryfield')),
            ],
            options={
                'ordering': ['field__display_order', 'field__name'],
            },
        ),
        migrations.AddIndex(
            model_name='categoryfield',
            index=models.Index(fields=['category', 'active'], name='category_field_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryfield',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='category_field_name_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='expensefieldvalue',
            index=models.Index(fields=['field'], name='expense_field_value_field_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensefieldvalue',
            constraint=models.UniqueConstraint(fields=('expense', 'field'), name='expense_field_value_unique'),
        ),
    ]
