# Generated by Django 5.2.4 on 2026-08-18 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAttribute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('LOCATION', 'Location'), ('DEPARTMENT', 'Department'), ('POSITION', 'Position')], max_length=16)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['dimension', 'name'],
                'indexes': [models.Index(fields=['dimension', 'active'], name='org_attribute_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('dimension', 'code'), name='org_attribute_dimension_code_unique')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_by_department', to='users.orgattribute'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_by_location', to='users.orgattribute'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_by_position', to='users.orgattribute'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['location', 'department', 'position'], name='users_org_attributes_idx'),
        ),
    ]
